"""Interaction knowledge pack cho semantic LLM judge.

Nội dung được tổng hợp từ `data/real_samples/question/interactions/index.md`
và các file chi tiết từng interaction type. Đây là nguồn tri thức nạp vào
prompt judge, không phải rule keyword và không dùng để auto-fix.
"""

from __future__ import annotations

from typing import Any


INTERACTION_KNOWLEDGE_SOURCE = "data/real_samples/question/interactions"


INTERACTION_TYPE_KNOWLEDGE: dict[str, dict[str, Any]] = {
    "single_choice": {
        "type": "single_choice",
        "status": "stable",
        "purpose": "Một câu hỏi trắc nghiệm có đúng một đáp án được chọn từ danh sách option.",
        "student_action": "Chọn một option; UI thường là radio hoặc card selectable, tại một thời điểm chỉ có một lựa chọn active.",
        "valid_when": [
            "Task yêu cầu chọn đúng một phương án trong một danh sách phương án.",
            "Generated interaction có `config.options` từ 2 phần tử trở lên, mỗi option có id ổn định.",
            "AnswerSpec dùng `expected.correctOptionId` trỏ tới một option id.",
            "Có thể là transform hợp lý từ câu tự luận ngắn sang trắc nghiệm nếu plan nói rõ sẽ generate options.",
        ],
        "invalid_when": [
            "Học sinh cần chọn nhiều đáp án độc lập.",
            "Không có option list hoặc UI không phải chọn từ danh sách.",
            "Task yêu cầu nhập tự do, nối cặp, sắp xếp, vẽ hoặc điền nhiều blank.",
        ],
        "required_or_typical_config_shape": [
            "`config.options[]` với `id` và `content`.",
            "`shuffleOptions` optional.",
            "`display.layout` thường auto/vertical/grid.",
        ],
        "answer_spec_shape": ["`type: single_choice`", "`expected.correctOptionId` là một option id."],
        "user_answer_shape": ["`value.selectedOptionId` là một option id."],
        "structural_evidence": ["options count >= 2", "correctOptionId", "selectedOptionId"],
        "semantic_evidence": ["chọn một đáp án", "một phương án đúng", "khẳng định nào đúng"],
        "common_confusions": ["multiple_choice", "true_false", "choice_blank_fill", "short_answer"],
        "distinguish_from": {
            "multiple_choice": "single_choice chỉ có một đáp án; multiple_choice cho phép tập đáp án.",
            "true_false": "true_false là hai giá trị boolean cố định, không phải danh sách option tùy biến.",
            "choice_blank_fill": "choice_blank_fill gắn option vào một blank inline giữa hai vế.",
            "short_answer": "short_answer không có option list, học sinh nhập tự do.",
        },
        "judge_notes": [
            "Không đánh sai chỉ vì source gốc không có sẵn A/B/C/D nếu plan/generation có ý định tạo options.",
            "Nếu generated structure không có options, cần review thay vì kết luận chỉ từ wording source.",
        ],
    },
    "multiple_choice": {
        "type": "multiple_choice",
        "status": "stable",
        "purpose": "Một câu hỏi có thể có nhiều lựa chọn đúng trong cùng danh sách.",
        "student_action": "Tick/chọn một hoặc nhiều option; UI thường là checkbox hoặc card multi-select.",
        "valid_when": [
            "Task yêu cầu chọn tất cả đáp án đúng hoặc nhiều phát biểu đúng.",
            "Generated interaction có `config.options[]` và answerSpec là tập `correctOptionIds`.",
            "Có `minSelections`/`maxSelections` như gợi ý UI nếu cần.",
        ],
        "invalid_when": [
            "Chỉ có đúng một phương án cần chọn.",
            "Task là nhiều mệnh đề đúng/sai từng dòng, nên cần boolean per statement.",
            "Task là tô/chọn đối tượng ảnh, nối cặp hoặc nhập tự do.",
        ],
        "required_or_typical_config_shape": [
            "`config.options[]` >= 2.",
            "`minSelections`, `maxSelections`, `shuffleOptions` optional.",
        ],
        "answer_spec_shape": ["`type: multiple_choice`", "`expected.correctOptionIds[]` là tập option ids."],
        "user_answer_shape": ["`value.selectedOptionIds[]` là tập option ids đã chọn."],
        "structural_evidence": ["correctOptionIds", "selectedOptionIds", "minSelections", "maxSelections"],
        "semantic_evidence": ["chọn tất cả", "các đáp án đúng", "nhiều lựa chọn đúng"],
        "common_confusions": ["single_choice", "true_false_multi_statement", "coloring_select"],
        "distinguish_from": {
            "single_choice": "single_choice chỉ chọn một option.",
            "true_false_multi_statement": "true_false_multi_statement đánh Đ/S từng statement, không chọn tập option.",
            "coloring_select": "coloring_select biểu diễn chọn nhiều bằng thao tác tô/chọn item ảnh.",
        },
        "judge_notes": ["Đừng yêu cầu raw source có sẵn option nếu plan tạo options trong generated question."],
    },
    "true_false": {
        "type": "true_false",
        "status": "stable",
        "purpose": "Đánh giá một mệnh đề duy nhất là đúng hay sai.",
        "student_action": "Chọn boolean đúng/sai qua hai nút, radio hoặc control tương đương.",
        "valid_when": [
            "Stem là một khẳng định đơn cần xác minh.",
            "Config có thể rỗng hoặc chỉ có nhãn true/false.",
            "AnswerSpec dùng `expected.correctValue: boolean`.",
        ],
        "invalid_when": [
            "Có nhiều statement cùng một ngữ cảnh trong một item.",
            "Cần chọn option tùy biến hoặc nhiều đáp án.",
            "Cần nhập/vẽ/sắp xếp/nối thay vì chọn boolean.",
        ],
        "required_or_typical_config_shape": ["`config` rỗng hoặc có `trueLabel`, `falseLabel`."],
        "answer_spec_shape": ["`type: true_false`", "`expected.correctValue` là boolean."],
        "user_answer_shape": ["`value.selectedValue` là boolean."],
        "structural_evidence": ["correctValue boolean", "selectedValue boolean", "trueLabel/falseLabel"],
        "semantic_evidence": ["một mệnh đề cần xác minh", "đúng hay sai", "có đúng không"],
        "common_confusions": ["single_choice", "multiple_choice", "true_false_multi_statement"],
        "distinguish_from": {
            "single_choice": "single_choice có option tùy biến; true_false chỉ có hai giá trị boolean.",
            "true_false_multi_statement": "multi_statement chứa nhiều statement cùng ngữ cảnh.",
        },
        "judge_notes": ["Một interaction true_false chỉ nên đại diện cho một mệnh đề chính."],
    },
    "true_false_multi_statement": {
        "type": "true_false_multi_statement",
        "status": "stable",
        "purpose": "Đánh giá nhiều mệnh đề đúng/sai cùng chia sẻ một ngữ cảnh.",
        "student_action": "Chọn Đ/S cho từng dòng statement trong danh sách.",
        "valid_when": [
            "Nhiều mệnh đề cùng tham chiếu một stem/hình/bảng/ngữ cảnh.",
            "`config.statements[]` >= 2, mỗi statement có id và content.",
            "AnswerSpec có `expected.answers[]` map statementId -> correctValue.",
        ],
        "invalid_when": [
            "Chỉ có một mệnh đề.",
            "Các mệnh đề độc lập nên tách thành nhiều item true_false.",
            "Task cần chọn một hoặc nhiều option tùy biến.",
        ],
        "required_or_typical_config_shape": ["`statements[]` với `id`, `content`; nhãn true/false optional."],
        "answer_spec_shape": ["`expected.answers[]` gồm `statementId`, `correctValue`."],
        "user_answer_shape": ["`value.answers[]` gồm `statementId`, `selectedValue`."],
        "structural_evidence": ["statements", "answers[].statementId", "answers[].correctValue"],
        "semantic_evidence": ["nhiều phát biểu cùng ngữ cảnh", "các khẳng định đúng/sai"],
        "common_confusions": ["true_false", "multiple_choice"],
        "distinguish_from": {
            "true_false": "true_false chỉ một statement.",
            "multiple_choice": "multiple_choice chọn tập option; multi_statement chấm boolean từng statement.",
        },
        "judge_notes": ["Nếu evidence nhiều statement yếu, ưu tiên warning/needs_review thay vì bad."],
    },
    "fill_blank": {
        "type": "fill_blank",
        "status": "stable",
        "purpose": "Điền một hoặc nhiều ô trống nằm trong một template văn bản/biểu thức.",
        "student_action": "Nhập hoặc chọn giá trị tại từng placeholder `[[blank_id]]` được nhúng inline trong template.",
        "valid_when": [
            "Task có template chứa chỗ trống rõ ràng trong câu, biểu thức, bảng hoặc đoạn văn.",
            "`config.template` chứa placeholder và `config.blanks[]` định nghĩa từng blank.",
            "Blank có thể là short_answer multi-mode hoặc text_options.",
        ],
        "invalid_when": [
            "Chỉ có một vùng nhập độc lập không nằm trong template.",
            "Task là đặt tính dọc, biến đổi từng dòng `=`, chuỗi phép tính ngang hoặc chọn option độc lập.",
            "Không có placeholder/template hoặc nhiều slot có quan hệ cấu trúc riêng ngoài template.",
        ],
        "required_or_typical_config_shape": [
            "`template`, `templateType`, `blanks[]`.",
            "Mỗi blank có `id`, `kind`, và shape theo `short_answer` hoặc `text_options`.",
        ],
        "answer_spec_shape": ["`expected.blanks[]` map `blankId` tới expected value hoặc correctOptionId."],
        "user_answer_shape": ["`value.blankAnswers[]` với `blankId`, kind, inputMode/value hoặc selectedOptionId."],
        "structural_evidence": ["template", "[[blank_id]]", "blanks", "blankAnswers"],
        "semantic_evidence": ["điền vào chỗ trống trong một mẫu có sẵn", "nhiều ô trong cùng câu/bảng"],
        "common_confusions": ["short_answer", "choice_blank_fill", "expression_transformation_step", "operation_chain"],
        "distinguish_from": {
            "short_answer": "short_answer là một ô nhập độc lập; fill_blank nhúng blank vào template.",
            "choice_blank_fill": "choice_blank_fill là một blank chọn option giữa leftContent/rightContent.",
            "expression_transformation_step": "expression_transformation_step chuyên các dòng biến đổi `=` với expressionStem.",
            "operation_chain": "operation_chain là node/mũi tên ngang, không phải template tự do.",
        },
        "judge_notes": ["Đừng kết luận chỉ từ chữ 'điền'; cần nhìn template/blanks hoặc plan intent."],
    },
    "short_answer": {
        "type": "short_answer",
        "status": "stable",
        "purpose": "Một vùng nhập tự do cho một đáp án ngắn.",
        "student_action": "Nhập text, số, phân số, hỗn số, lũy thừa, căn hoặc LaTeX theo inputMode được config.",
        "valid_when": [
            "Task yêu cầu một giá trị ngắn hoặc một biểu thức/công thức trong một ô nhập độc lập.",
            "`config.defaultInputMode` nằm trong `modeConfigs[].inputMode`.",
            "Có một hoặc nhiều mode: text, numeric, fraction, mixed_number, power, root, latex.",
        ],
        "invalid_when": [
            "Task cần nhiều blank nhúng trong template.",
            "Task cần nhiều tọa độ/hàng/thành phần cấu trúc.",
            "Task cần nối, sắp xếp, chọn option, vẽ hoặc đặt tính dọc nhiều slot.",
        ],
        "required_or_typical_config_shape": [
            "`defaultInputMode`, `modeConfigs[]`, optional `unit`, `unitPosition`.",
            "Mode latex có toolbar; numeric có allowDecimal/allowNegative; fraction/mixed_number/power/root có value object riêng.",
        ],
        "answer_spec_shape": ["`expected[]` một entry per modeConfig, mỗi entry có value + equivalence."],
        "user_answer_shape": ["`inputMode` và `value` theo mode đã chọn."],
        "structural_evidence": ["defaultInputMode", "modeConfigs", "inputMode", "expected[] mode union"],
        "semantic_evidence": ["nhập đáp án ngắn", "một giá trị", "một công thức/biểu thức", "không có option list"],
        "common_confusions": ["fill_blank", "coordinate_input", "column_arithmetic", "single_choice"],
        "distinguish_from": {
            "fill_blank": "fill_blank đặt blank trong template; short_answer là một block nhập độc lập.",
            "coordinate_input": "coordinate_input có nhiều hàng/thành phần tọa độ, không phải một ô duy nhất.",
            "column_arithmetic": "column_arithmetic có nhiều slot căn cột theo phép tính dọc.",
            "single_choice": "single_choice chọn từ options, không nhập tự do.",
        },
        "judge_notes": [
            "Latex phù hợp với công thức/phương trình/biểu thức nhập tự do.",
            "Nếu cần nhiều slot có cấu trúc, short_answer một ô có thể chưa phù hợp.",
        ],
    },
    "matching": {
        "type": "matching",
        "status": "stable",
        "purpose": "Ghép cặp giữa hai tập phần tử trái/phải.",
        "student_action": "Tạo link giữa một item bên trái và một item bên phải; cardinality theo matchingMode.",
        "valid_when": [
            "Task yêu cầu nối khái niệm-kết quả, phép tính-đáp án, hình-mô tả hoặc quan hệ hai tập.",
            "`config.leftItems[]` và `config.rightItems[]` là hai tập riêng.",
            "AnswerSpec dùng `expected.groups[]` hoặc userAnswer dùng `links[]`.",
        ],
        "invalid_when": [
            "Chỉ sắp xếp một danh sách.",
            "Điền blank trong template hoặc nhập tự do.",
            "Kéo thẻ vào vùng đích thay vì nối giữa hai cột.",
        ],
        "required_or_typical_config_shape": [
            "`matchingMode`, `layout`, `leftItems[]`, `rightItems[]`.",
            "`leftItems/rightItems` có id và content; media item cần visualDescriptionForAi.",
        ],
        "answer_spec_shape": ["`expected.groups[]` với leftIds/rightIds, hoặc expanded links."],
        "user_answer_shape": ["`value.links[]` gồm `{leftId, rightId}`."],
        "structural_evidence": ["leftItems", "rightItems", "matchingMode", "groups", "links"],
        "semantic_evidence": ["ghép cặp hai tập", "nối tương ứng", "quan hệ bipartite"],
        "common_confusions": ["ordering", "fill_blank", "short_answer", "drag_drop"],
        "distinguish_from": {
            "ordering": "ordering sắp xếp một tập item; matching tạo cặp giữa hai tập.",
            "fill_blank": "fill_blank điền chỗ trống, không tạo liên kết trái-phải.",
            "short_answer": "short_answer nhập một đáp án tự do.",
            "drag_drop": "drag_drop kéo item vào vùng đích; matching nối hai phía.",
        },
        "judge_notes": ["Không kết luận chỉ vì text có chữ 'ghép'; cần evidence có hai tập hoặc plan/generation hướng tới nối cặp."],
    },
    "ordering": {
        "type": "ordering",
        "status": "stable",
        "purpose": "Sắp xếp lại thứ tự một danh sách item.",
        "student_action": "Reorder các item bằng kéo thả hoặc nút lên/xuống.",
        "valid_when": [
            "Task yêu cầu thứ tự đúng của bước giải, mốc thời gian, quy trình hoặc ranking.",
            "`config.items[]` là một danh sách item và answerSpec có `correctOrder[]`.",
        ],
        "invalid_when": [
            "Task yêu cầu nối hai tập phần tử.",
            "Task yêu cầu kéo item vào nhiều vùng đích hoặc điền blank.",
            "Không có quan hệ thứ tự một chiều.",
        ],
        "required_or_typical_config_shape": ["`items[]`, optional `shuffleItems`."],
        "answer_spec_shape": ["`expected.correctOrder[]` là hoán vị đầy đủ của item ids."],
        "user_answer_shape": ["`value.orderedItemIds[]` là hoán vị học sinh sắp."],
        "structural_evidence": ["items", "correctOrder", "orderedItemIds"],
        "semantic_evidence": ["sắp xếp thứ tự", "các bước", "trình tự"],
        "common_confusions": ["matching", "drag_drop", "operation_chain"],
        "distinguish_from": {
            "matching": "matching tạo cặp giữa hai tập; ordering chỉ sắp một danh sách.",
            "drag_drop": "drag_drop đưa item vào target vùng đích; ordering chỉ reorder.",
            "operation_chain": "operation_chain là chuỗi phép tính có node và mũi tên cố định.",
        },
        "judge_notes": ["Nếu plan tạo các bước chứng minh để sắp xếp, ordering có thể là transform hợp lý từ bài chứng minh."],
    },
    "drag_drop": {
        "type": "drag_drop",
        "status": "todo",
        "purpose": "Dự kiến cho thao tác kéo thả item vào vùng đích.",
        "student_action": "Kéo item vào target/drop zone; spec chi tiết chưa chốt.",
        "valid_when": [
            "Có evidence rõ về draggable items và drop targets.",
            "Generated structure thể hiện vùng đích/thẻ kéo thả dù spec chính thức còn TODO.",
        ],
        "invalid_when": [
            "Chỉ nối cặp trái/phải, sắp xếp danh sách, hoặc chọn option.",
            "Không có thông tin về drop zones/draggable items.",
        ],
        "required_or_typical_config_shape": ["Spec TODO; kỳ vọng có items và target/drop zones khi triển khai."],
        "answer_spec_shape": ["Spec TODO; kỳ vọng mapping item -> target."],
        "user_answer_shape": ["Spec TODO; kỳ vọng placement/submission của item vào target."],
        "structural_evidence": ["draggable items", "drop targets", "placements"],
        "semantic_evidence": ["kéo thả vào vùng đích", "phân loại item vào vùng"],
        "common_confusions": ["matching", "ordering", "fill_blank"],
        "distinguish_from": {
            "matching": "matching nối hai phía bằng links; drag_drop đặt item vào vùng.",
            "ordering": "ordering chỉ reorder một list.",
            "fill_blank": "fill_blank nhập/chọn tại placeholder.",
        },
        "judge_notes": ["Vì spec TODO, nếu evidence không rõ thì trả needs_review thay vì bad/ok quá chắc."],
    },
    "number_line_range": {
        "type": "number_line_range",
        "status": "stable",
        "purpose": "Vẽ điểm, đoạn hoặc tia trên trục số 1D.",
        "student_action": "Đặt point/segment/ray trên trục số, có thể snap theo bước.",
        "valid_when": [
            "Task yêu cầu biểu diễn miền nghiệm, bất phương trình, khoảng giá trị hoặc điểm trên trục số.",
            "`config.axis` và `allowedObjectTypes` mô tả trục và công cụ vẽ.",
            "AnswerSpec có `expected.objects[]` kiểu point/segment/ray.",
        ],
        "invalid_when": [
            "Task yêu cầu vẽ trên mặt phẳng tọa độ 2D.",
            "Task chỉ nhập tọa độ/số vào ô.",
            "Task là chart/statistics hoặc lựa chọn option.",
        ],
        "required_or_typical_config_shape": ["`axis`, `allowedObjectTypes`, optional `predrawnObjects`, `limits`, `snapStep`."],
        "answer_spec_shape": ["`expected.objects[]` gồm point/segment/ray."],
        "user_answer_shape": ["`value.objects[]` gồm point/segment/ray học sinh vẽ."],
        "structural_evidence": ["axis", "allowedObjectTypes point/segment/ray", "predrawnObjects", "snapStep"],
        "semantic_evidence": ["trục số 1D", "miền nghiệm/khoảng/tia/đoạn trên trục"],
        "common_confusions": ["graph_draw", "coordinate_input", "short_answer"],
        "distinguish_from": {
            "graph_draw": "graph_draw là mặt phẳng tọa độ 2D.",
            "coordinate_input": "coordinate_input là nhập tọa độ, không vẽ.",
            "short_answer": "short_answer nhập một giá trị, không thao tác trên trục.",
        },
        "judge_notes": ["Nếu generated chỉ có content block trục số tĩnh, không phải interaction vẽ thì cần review."],
    },
    "image_hotspot": {
        "type": "image_hotspot",
        "status": "todo",
        "purpose": "Dự kiến cho việc chọn vùng/tọa độ trên một ảnh duy nhất.",
        "student_action": "Click/tap một hoặc nhiều vùng hotspot trên ảnh; spec chi tiết chưa chốt.",
        "valid_when": [
            "Có một ảnh nền và vùng hotspot/tọa độ cần chọn.",
            "Generated structure thể hiện image + regions/hotspots.",
        ],
        "invalid_when": [
            "Các đối tượng là item ảnh rời để tô/chọn.",
            "Task chỉ chọn option text/card hoặc vẽ trên graph.",
        ],
        "required_or_typical_config_shape": ["Spec TODO; kỳ vọng có image source, hotspot regions hoặc coordinate zones."],
        "answer_spec_shape": ["Spec TODO; kỳ vọng correct region ids/coordinates."],
        "user_answer_shape": ["Spec TODO; kỳ vọng selected region ids hoặc click coordinates."],
        "structural_evidence": ["image", "hotspots", "regions", "coordinates"],
        "semantic_evidence": ["chọn vùng trên hình/ảnh duy nhất"],
        "common_confusions": ["coloring_select", "single_choice", "graph_draw"],
        "distinguish_from": {
            "coloring_select": "coloring_select chọn/tô các item ảnh rời có id; image_hotspot chọn vùng trên một ảnh.",
            "single_choice": "single_choice chọn option list, không click vùng ảnh.",
            "graph_draw": "graph_draw vẽ object trên hệ trục, không chọn hotspot ảnh tự do.",
        },
        "judge_notes": ["Spec TODO nên thiếu generated evidence rõ thì trả needs_review."],
    },
    "coloring_select": {
        "type": "coloring_select",
        "status": "stable",
        "purpose": "Tô màu hoặc toggle chọn nhiều item hình ảnh rời.",
        "student_action": "Click/tap các item để chuyển trạng thái đã tô/chưa tô.",
        "valid_when": [
            "Task yêu cầu lọc/chọn nhiều đối tượng trực quan theo tiêu chí.",
            "`config.items[]` có id, imageContent, imageUrl.",
            "AnswerSpec dùng `correctItemIds[]`.",
        ],
        "invalid_when": [
            "Chọn vùng trên một ảnh duy nhất.",
            "Chọn option text/card thông thường.",
            "Vẽ hoặc nhập giá trị.",
        ],
        "required_or_typical_config_shape": ["`items[]`, optional min/max selections, shuffleItems."],
        "answer_spec_shape": ["`expected.correctItemIds[]`."],
        "user_answer_shape": ["`value.selectedItemIds[]`."],
        "structural_evidence": ["items.imageUrl", "imageContent", "correctItemIds", "selectedItemIds"],
        "semantic_evidence": ["tô màu/chọn nhiều vật thể ảnh rời", "lọc đối tượng trực quan"],
        "common_confusions": ["multiple_choice", "image_hotspot"],
        "distinguish_from": {
            "multiple_choice": "multiple_choice là option list; coloring_select là item ảnh được tô/chọn.",
            "image_hotspot": "image_hotspot chọn vùng trên một ảnh nền duy nhất.",
        },
        "judge_notes": ["Nếu generated không có imageUrl/item ảnh, multiple_choice có thể hợp hơn nhưng judge chỉ kết luận mismatch nếu evidence rõ."],
    },
    "column_arithmetic": {
        "type": "column_arithmetic",
        "status": "stable",
        "purpose": "Đặt tính dọc và điền các slot trong các bước phép tính cột.",
        "student_action": "Điền số vào nhiều slot căn cột trong các hàng cộng/trừ/nhân/chia/equal.",
        "valid_when": [
            "Task yêu cầu đặt tính dọc hoặc hoàn thành phép tính theo cột.",
            "`config.steps[]` chứa equations, operators và slots căn cột.",
            "Blank slots tham chiếu bằng key; answerSpec có `answers[]` với targetSlotKey/correctValue.",
        ],
        "invalid_when": [
            "Task chỉ yêu cầu một kết quả ngắn hoặc một công thức.",
            "Task là biến đổi biểu thức dòng `=`, chuỗi phép tính ngang, chart, graph, matching hoặc ordering.",
            "Generated structure không có slots/steps/operator của đặt tính dọc.",
        ],
        "required_or_typical_config_shape": ["`steps[].equation.operator`", "`steps[].equation.slots[]`", "slot `key`, `isBlank`, `value` hoặc `blankWidth`."],
        "answer_spec_shape": ["`expected.answers[]` gồm `targetSlotKey`, `correctValue`."],
        "user_answer_shape": ["`value.slotValues[]` gồm `slotKey`, `value`."],
        "structural_evidence": ["steps", "equation.operator", "slots", "targetSlotKey", "slotValues"],
        "semantic_evidence": ["đặt tính dọc", "nhiều ô căn theo hàng đơn vị/chục/trăm", "cộng/trừ/nhân/chia dạng cột"],
        "common_confusions": ["short_answer", "fill_blank", "expression_transformation_step", "operation_chain"],
        "distinguish_from": {
            "short_answer": "short_answer là một ô nhập, không có lưới cột.",
            "fill_blank": "fill_blank là template tự do, không có operator/slot theo cột.",
            "expression_transformation_step": "expression_transformation_step là các dòng `=` trong biến đổi biểu thức.",
            "operation_chain": "operation_chain là chuỗi ngang node/mũi tên.",
        },
        "judge_notes": [
            "Không xem column_arithmetic là type chung cho mọi bài tính toán.",
            "Chỉ đánh bad khi plan/generated cho thấy type này không thể phục vụ UI/task, không chỉ vì một keyword.",
        ],
    },
    "choice_blank_fill": {
        "type": "choice_blank_fill",
        "status": "stable",
        "purpose": "Chọn một option để điền vào một blank inline giữa leftContent và rightContent.",
        "student_action": "Chọn ký hiệu/toán tử/lựa chọn ngắn từ options để lấp ô giữa hai vế.",
        "valid_when": [
            "Task có một blank cố định giữa hai vế nội dung.",
            "Options là danh sách lựa chọn ngắn; answerSpec có `correctOptionId`.",
            "Phù hợp với so sánh, chọn dấu quan hệ hoặc phép toán giữa hai vế.",
        ],
        "invalid_when": [
            "Có nhiều blank trong template tự do.",
            "Câu là trắc nghiệm option list độc lập.",
            "Cần nhập tự do thay vì chọn từ options.",
        ],
        "required_or_typical_config_shape": ["`leftContent`, `rightContent`, `options[]`, optional shuffleOptions."],
        "answer_spec_shape": ["`expected.correctOptionId`."],
        "user_answer_shape": ["`value.selectedOptionId`."],
        "structural_evidence": ["leftContent", "rightContent", "options", "correctOptionId"],
        "semantic_evidence": ["điền dấu/ký hiệu vào blank giữa hai vế", "so sánh hoặc chọn phép toán inline"],
        "common_confusions": ["single_choice", "fill_blank", "short_answer"],
        "distinguish_from": {
            "single_choice": "single_choice hiển thị option list riêng; choice_blank_fill là blank inline giữa hai content.",
            "fill_blank": "fill_blank có template và có thể nhiều blank/kind; choice_blank_fill là một blank chọn option giữa hai vế.",
            "short_answer": "short_answer nhập tự do, không chọn option.",
        },
        "judge_notes": ["Nếu generated có template nhiều blank, fill_blank thường phù hợp hơn."],
    },
    "expression_transformation_step": {
        "type": "expression_transformation_step",
        "status": "stable",
        "purpose": "Hoàn thành các bước biến đổi biểu thức theo nhiều dòng bắt đầu bằng dấu bằng.",
        "student_action": "Điền từng blank trong các dòng step/template bên dưới expressionStem.",
        "valid_when": [
            "Task yêu cầu trình bày hoặc hoàn thành biến đổi biểu thức từng bước.",
            "`config.expressionStem` và `steps[].template` chứa placeholders.",
            "AnswerSpec map mỗi blankId tới expected short_answer modes.",
        ],
        "invalid_when": [
            "Chỉ cần kết quả cuối trong một ô.",
            "Blank nằm trong văn bản/template tự do không phải chuỗi biến đổi.",
            "Task là đặt tính dọc hoặc chuỗi phép tính ngang node/mũi tên.",
        ],
        "required_or_typical_config_shape": ["`expressionStem`, `steps[]`, mỗi step có `template` và `blanks[]`."],
        "answer_spec_shape": ["`expected.blanks[]` với blankId và expected mode entries."],
        "user_answer_shape": ["`value.blankAnswers[]` với blankId, inputMode, value."],
        "structural_evidence": ["expressionStem", "steps.template", "[[blank_id]]", "blankAnswers"],
        "semantic_evidence": ["biến đổi biểu thức từng bước", "dòng bằng", "hoàn thành bước tính"],
        "common_confusions": ["fill_blank", "short_answer", "column_arithmetic", "operation_chain"],
        "distinguish_from": {
            "fill_blank": "fill_blank template tự do; expression_transformation_step có expressionStem và các dòng step.",
            "short_answer": "short_answer chỉ một đáp án cuối.",
            "column_arithmetic": "column_arithmetic căn cột dọc, không phải dòng `=`.",
            "operation_chain": "operation_chain là node/mũi tên ngang.",
        },
        "judge_notes": ["Nếu generated chỉ có một input cuối, cần cân nhắc short_answer thay vì type này."],
    },
    "operation_chain": {
        "type": "operation_chain",
        "status": "stable",
        "purpose": "Điền ô trong chuỗi phép tính ngang gồm node và mũi tên operation.",
        "student_action": "Điền các node input trong chuỗi từ trái sang phải; operation trên mũi tên chỉ hiển thị.",
        "valid_when": [
            "Task có dạng ô số nối bằng mũi tên phép toán ngang.",
            "`config.steps[]` >= 2, step đầu là given, các step sau thường là input.",
            "AnswerSpec dùng `expected.blanks[]` theo node/blank id.",
        ],
        "invalid_when": [
            "Task là đặt tính dọc.",
            "Task là biến đổi biểu thức dòng `=`.",
            "Task chỉ điền blank trong câu văn/template tự do.",
        ],
        "required_or_typical_config_shape": ["`colorCode`, `steps[]`, node role given/input, operation kind/operand/displayLabel."],
        "answer_spec_shape": ["`expected.blanks[]` giống fill_blank."],
        "user_answer_shape": ["`value.blankAnswers[]` giống fill_blank."],
        "structural_evidence": ["steps.node", "operation", "colorCode", "blankAnswers"],
        "semantic_evidence": ["chuỗi phép tính ngang", "ô và mũi tên", "điền số vào node"],
        "common_confusions": ["fill_blank", "column_arithmetic", "expression_transformation_step"],
        "distinguish_from": {
            "fill_blank": "fill_blank là template; operation_chain là graph ngang node/mũi tên.",
            "column_arithmetic": "column_arithmetic là phép tính dọc.",
            "expression_transformation_step": "expression_transformation_step là dòng `=`.",
        },
        "judge_notes": ["Operation không phải server-side arithmetic; evidence chính là shape node/operation."],
    },
    "chart_draw": {
        "type": "chart_draw",
        "status": "design",
        "purpose": "Vẽ biểu đồ thống kê từ dữ liệu/bảng cho trước.",
        "student_action": "Gán giá trị cho từng hạng mục trên biểu đồ cột, đoạn thẳng hoặc quạt tròn.",
        "valid_when": [
            "Task yêu cầu vẽ biểu đồ thống kê.",
            "`config.chartType` là bar/line/pie và có categories.",
            "AnswerSpec có `expected.data[]` categoryKey/value.",
        ],
        "invalid_when": [
            "Task chỉ hỏi đọc/chọn thông tin từ biểu đồ có sẵn.",
            "Task yêu cầu vẽ hình/đồ thị tọa độ 2D không phải chart thống kê.",
            "Task chỉ nhập vài số vào ô.",
        ],
        "required_or_typical_config_shape": ["`chartType`, `categories[]`, axis config cho bar/line, valueMode cho pie."],
        "answer_spec_shape": ["`expected.data[]` gồm `categoryKey`, `value`, optional tolerance."],
        "user_answer_shape": ["`value.data[]` gồm `categoryKey`, `value`."],
        "structural_evidence": ["chartType", "categories", "categoryAxis", "valueAxis", "valueMode", "data"],
        "semantic_evidence": ["vẽ biểu đồ cột/đoạn thẳng/quạt tròn", "bảng tần số/tần số tương đối"],
        "common_confusions": ["graph_draw", "short_answer", "single_choice"],
        "distinguish_from": {
            "graph_draw": "graph_draw vẽ object hình học/hàm trên mặt phẳng tọa độ; chart_draw vẽ biểu đồ thống kê.",
            "short_answer": "short_answer nhập giá trị, không thao tác trên biểu đồ.",
            "single_choice": "single_choice chỉ chọn loại/đáp án, không vẽ chart.",
        },
        "judge_notes": ["Type đang ở trạng thái thiết kế; nếu evidence chưa đủ rõ, trả needs_review."],
    },
    "coordinate_input": {
        "type": "coordinate_input",
        "status": "stable",
        "purpose": "Nhập một hoặc nhiều điểm/tọa độ có nhiều thành phần.",
        "student_action": "Gõ từng hàng tọa độ `(comp0, comp1, ...)`, cố định hoặc thêm/xóa hàng.",
        "valid_when": [
            "Task yêu cầu nhập tọa độ, nghiệm dạng cặp/bộ, giao điểm hoặc tập điểm.",
            "`config.dimensions`, `countMode`, `modeConfigs`, `grading` mô tả cấu trúc nhiều thành phần.",
            "AnswerSpec có `expected.coordinates[]` hoặc null.",
        ],
        "invalid_when": [
            "Task yêu cầu vẽ điểm/đường trên canvas.",
            "Chỉ cần một số/biểu thức đơn.",
            "Task là trắc nghiệm hoặc matching.",
        ],
        "required_or_typical_config_shape": [
            "`dimensions`, `dimensionLabels`, `defaultInputMode`, `modeConfigs`, `grading`.",
            "`countMode: fixed` có `slots[]`; `variable` có `limits`.",
        ],
        "answer_spec_shape": ["`expected.coordinates[]` gồm rows với inputMode và components."],
        "user_answer_shape": ["`value.coordinates[]` hoặc null; mỗi row có components."],
        "structural_evidence": ["dimensions", "countMode", "coordinates", "components", "slots", "limits"],
        "semantic_evidence": ["nhập tọa độ/cặp số/tập nghiệm", "nhiều hàng hoặc nhiều thành phần"],
        "common_confusions": ["short_answer", "graph_draw", "number_line_range"],
        "distinguish_from": {
            "short_answer": "short_answer là một ô; coordinate_input có rows x components.",
            "graph_draw": "graph_draw vẽ object trên canvas.",
            "number_line_range": "number_line_range vẽ trên trục số 1D.",
        },
        "judge_notes": ["Nếu chỉ có một giá trị số không mang cấu trúc tọa độ, short_answer có thể phù hợp hơn."],
    },
    "graph_draw": {
        "type": "graph_draw",
        "status": "design",
        "purpose": "Vẽ object trên mặt phẳng tọa độ 2D.",
        "student_action": "Dùng toolbar/canvas để đặt point, polygon, polyline, circle, segment, ray, line hoặc quadratic.",
        "valid_when": [
            "Task yêu cầu vẽ/biểu diễn hình học tọa độ, đồ thị hàm, hệ phương trình hoặc object 2D.",
            "`config.axes`, `grid`, `allowedObjectTypes` và toolbar/limits/slots mô tả canvas.",
            "AnswerSpec có `expected.objects[]` là object hình học.",
        ],
        "invalid_when": [
            "Task chỉ nhập tọa độ bằng text.",
            "Task là chart thống kê hoặc trục số 1D.",
            "Task chỉ chọn option hay nhập công thức.",
        ],
        "required_or_typical_config_shape": [
            "`axes`, `grid`, `allowedObjectTypes`, optional `predrawnObjects`, `limits`, `slots`, `toolbarMode`, `snapStep`, `grading`.",
        ],
        "answer_spec_shape": ["`expected.objects[]` gồm graph draw objects, optional slotId khi by_slot."],
        "user_answer_shape": ["`value.objects[]` gồm submitted graph objects."],
        "structural_evidence": ["axes", "grid", "allowedObjectTypes", "toolbarMode", "objects", "slotId"],
        "semantic_evidence": ["vẽ trên mặt phẳng tọa độ", "đồ thị hàm", "điểm/đường/đa giác/circle/line/quadratic"],
        "common_confusions": ["coordinate_input", "number_line_range", "chart_draw"],
        "distinguish_from": {
            "coordinate_input": "coordinate_input gõ tọa độ; graph_draw thao tác trên canvas 2D.",
            "number_line_range": "number_line_range chỉ 1D trục số.",
            "chart_draw": "chart_draw là biểu đồ thống kê category/value.",
        },
        "judge_notes": ["Type đang ở trạng thái thiết kế; nếu generated canvas/tooling không rõ thì trả needs_review."],
    },
}


def compact_interaction_knowledge() -> dict[str, dict[str, Any]]:
    """Trả knowledge pack đủ gọn để đưa vào prompt nhưng vẫn giữ tiêu chí phân biệt."""

    return {
        name: {
            key: value
            for key, value in knowledge.items()
            if key
            in {
                "status",
                "purpose",
                "student_action",
                "valid_when",
                "invalid_when",
                "required_or_typical_config_shape",
                "answer_spec_shape",
                "user_answer_shape",
                "structural_evidence",
                "semantic_evidence",
                "common_confusions",
                "distinguish_from",
                "judge_notes",
            }
        }
        for name, knowledge in INTERACTION_TYPE_KNOWLEDGE.items()
    }
